"""Generates installer/AaryaVoiceLabDefines.iss from configs/release.yaml,
so the Inno Setup script never carries a second, independently-maintained
copy of product name/version/app id -- the same single-source-of-truth
discipline docs/WINDOWS_RELEASE.md already establishes for a future
installer manifest. Run before compiling installer/AaryaVoiceLab.iss (see
docs/INDICF5_INSTALLER.md's "Windows installer artifact" section for the
full build command).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from aarya_voice_lab.release import load_release_metadata  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "installer" / "AaryaVoiceLabDefines.iss"


def _iss_escape(value: str) -> str:
    return value.replace('"', '""')


def main() -> int:
    metadata = load_release_metadata()
    lines = [
        "; GENERATED by scripts/generate_installer_defines.py from configs/release.yaml.",
        "; Do not edit by hand -- edit configs/release.yaml and regenerate.",
        f'#define MyAppName "{_iss_escape(metadata.product_name)}"',
        f'#define MyAppId "{_iss_escape(metadata.app_id)}"',
        f'#define MyAppVersion "{_iss_escape(metadata.version)}"',
        f'#define MyAppPublisher "{_iss_escape(metadata.publisher)}"',
    ]
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
